### ISSUE TITLE
Projects created with this template will contain a copyright statement for Ashley Williams

### ISSUE THREAD

**Issue by maddiemort** [sassman/hermit-template-rs#1]
The first line of the LICENSE-MIT file in this repository says:

> Copyright (c) 2018 Ashley Williams

As far as I understand, this line will not be changed by `cargo-generate`, and so any projects generated with this template will contain that exact copyright statement.

**Comment by sassman** [comment]
oh, a very good catch!

**Comment by sassman** [comment]
fixed with using the `{{ authors }}` placeholder
